In [3]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

In [4]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage= requests.get("https://www.ambitionbox.com/list-of-companies?search=CGI&page=1", headers=headers)

In [5]:
soup= BeautifulSoup(webpage.text, 'lxml')
#print(soup.prettify())

In [7]:
company= soup.find_all('div', class_="companyCardWrapper")
len(company)

20

In [20]:
company[0].find('div', class_="rating_text").text.strip()
lnt= company[0].find('span', class_="companyCardWrapper__interLinking")
#lnt

In [52]:

final=pd.DataFrame()

for j in range(1,500):
    
    webpage= requests.get("https://www.ambitionbox.com/list-of-companies?search=CGI&page=1", headers=headers)
    soup= BeautifulSoup(webpage.text, 'lxml')
    name=[]
    reviews=[]
    location=[]
    ctype=[]
    jobs=[]
    ratings=[]

    for i in company:
        name.append(i.find('h2').text.strip())
        ratings.append(i.find('div', class_="rating_text").text.strip())
        reviews.append(i.find('span', class_="companyCardWrapper__companyRatingCount").text.strip().replace("(", "").replace(")", ""))
        lnt= i.find('span', class_="companyCardWrapper__interLinking")
        temp= lnt.text.strip().split('|')
        ctype.append(temp[0])
        location.append(temp[1])
        jobs.append(i.find_all('span', class_="companyCardWrapper__ActionCount")[3].text.strip())

    df=pd.DataFrame({'name':name,
    'rating':ratings,
    'reviews':reviews,
    'company_type':ctype,
    'Location': location,
    'Job_opening':jobs,
    })
  
    final=pd.concat([final,df],ignore_index=True)

In [51]:
final

,name,rating,reviews,company_type,Location,Job_opening
0,TCS,3.3,1.1L,IT Services & Consulting,Bengaluru +444 other locations,4.6k
1,Accenture,3.7,73.7k,IT Services & Consulting,Bengaluru +259 other locations,37.8k
2,Wipro,3.6,65.3k,IT Services & Consulting,Hyderabad +373 other locations,335
3,Cognizant,3.7,61.7k,IT Services & Consulting,Hyderabad +232 other locations,591
4,Capgemini,3.6,53.6k,IT Services & Consulting,Bengaluru +182 other locations,2.3k
...,...,...,...,...,...,...
975,Amazon,3.9,31.6k,Internet,Bengaluru +515 other locations,73
976,Reliance Retail,3.9,27.4k,Retail,Mumbai +1161 other locations,104
977,iEnergizer,4.6,27.2k,BPO,Noida +53 other locations,94
978,LTIMindtree,3.6,26.6k,IT Services & Consulting,Bengaluru +145 other locations,541
979,IBM,3.9,25.9k,IT Services & Consulting,Bengaluru +162 other locations,1.4k

In [53]:
final

,name,rating,reviews,company_type,Location,Job_opening
0,TCS,3.3,1.1L,IT Services & Consulting,Bengaluru +444 other locations,4.6k
1,Accenture,3.7,73.7k,IT Services & Consulting,Bengaluru +259 other locations,37.8k
2,Wipro,3.6,65.3k,IT Services & Consulting,Hyderabad +373 other locations,335
3,Cognizant,3.7,61.7k,IT Services & Consulting,Hyderabad +232 other locations,591
4,Capgemini,3.6,53.6k,IT Services & Consulting,Bengaluru +182 other locations,2.3k
...,...,...,...,...,...,...
9975,Amazon,3.9,31.6k,Internet,Bengaluru +515 other locations,73
9976,Reliance Retail,3.9,27.4k,Retail,Mumbai +1161 other locations,104
9977,iEnergizer,4.6,27.2k,BPO,Noida +53 other locations,94
9978,LTIMindtree,3.6,26.6k,IT Services & Consulting,Bengaluru +145 other locations,541
9979,IBM,3.9,25.9k,IT Services & Consulting,Bengaluru +162 other locations,1.4k

In [54]:
final.to_csv('companies.csv', index=False)